# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Fri Oct 25 13:29:35 2019
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 728)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.homeTab)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.groupBox_21 = QtWidgets.QGroupBox(self.homeTab)
        self.groupBox_21.setMaximumSize(QtCore.QSize(800, 16777215))
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_58 = QtWidgets.QLabel(self.groupBox_21)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_26.addWidget(self.label_58, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_21, 0, 0, 1, 1)
        self.groupBox_22 = QtWidgets.QGroupBox(self.homeTab)
        self.groupBox_22.setMaximumSize(QtCore.QSize(800, 16777215))
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_25.addWidget(self.groupBox_22, 1, 0, 1, 1)
        self.tabWidget.addTab(self.homeTab, "")
        self.unitConverterTab = QtWidgets.QWidget()
        self.unitConverterTab.setObjectName("unitConverterTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.unitConverterTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_3.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_4.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_16.addWidget(self.lineEdit_14)
        self.comboBox_16 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_16.setObjectName("comboBox_16")
        self.horizontalLayout_16.addWidget(self.comboBox_16)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_15.addWidget(self.lineEdit_13)
        self.comboBox_15 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_15.setObjectName("comboBox_15")
        self.horizontalLayout_15.addWidget(self.comboBox_15)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_5.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_6.addWidget(self.comboBox_6)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout_5.addWidget(self.comboBox_5)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_6.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_6.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_18.addWidget(self.lineEdit_16)
        self.comboBox_18 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_18.setObjectName("comboBox_18")
        self.horizontalLayout_18.addWidget(self.comboBox_18)
        self.gridLayout_11.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_17.addWidget(self.lineEdit_15)
        self.comboBox_17 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_17.setObjectName("comboBox_17")
        self.horizontalLayout_17.addWidget(self.comboBox_17)
        self.gridLayout_11.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_7.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_7.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_10.addWidget(self.lineEdit_8)
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_10.setObjectName("comboBox_10")
        self.horizontalLayout_10.addWidget(self.comboBox_10)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_9.addWidget(self.lineEdit_7)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_9.addWidget(self.comboBox_9)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_7, 2, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_8.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_8.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_20.addWidget(self.lineEdit_18)
        self.comboBox_20 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_20.setObjectName("comboBox_20")
        self.horizontalLayout_20.addWidget(self.comboBox_20)
        self.gridLayout_12.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_19.addWidget(self.lineEdit_17)
        self.comboBox_19 = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_19.setObjectName("comboBox_19")
        self.horizontalLayout_19.addWidget(self.comboBox_19)
        self.gridLayout_12.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 2, 1, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_9.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_9.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_12.addWidget(self.lineEdit_10)
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_12.setObjectName("comboBox_12")
        self.horizontalLayout_12.addWidget(self.comboBox_12)
        self.gridLayout_9.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_9)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_11.addWidget(self.lineEdit_9)
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_11.setObjectName("comboBox_11")
        self.horizontalLayout_11.addWidget(self.comboBox_11)
        self.gridLayout_9.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_9, 3, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_10.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_10.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(self.groupBox_10)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_22.addWidget(self.lineEdit_20)
        self.comboBox_22 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_22.setObjectName("comboBox_22")
        self.horizontalLayout_22.addWidget(self.comboBox_22)
        self.gridLayout_13.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_21.addWidget(self.lineEdit_19)
        self.comboBox_21 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_21.setObjectName("comboBox_21")
        self.horizontalLayout_21.addWidget(self.comboBox_21)
        self.gridLayout_13.addLayout(self.horizontalLayout_21, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_10, 3, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_11.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_11.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_14.addWidget(self.lineEdit_12)
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_14.setObjectName("comboBox_14")
        self.horizontalLayout_14.addWidget(self.comboBox_14)
        self.gridLayout_10.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_13.addWidget(self.lineEdit_11)
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_13.setObjectName("comboBox_13")
        self.horizontalLayout_13.addWidget(self.comboBox_13)
        self.gridLayout_10.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_11, 4, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_12.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_12.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtWidgets.QLabel(self.groupBox_12)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_24.addWidget(self.lineEdit_26)
        self.comboBox_24 = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_24.setObjectName("comboBox_24")
        self.horizontalLayout_24.addWidget(self.comboBox_24)
        self.gridLayout_14.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_23.addWidget(self.lineEdit_25)
        self.comboBox_23 = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_23.setObjectName("comboBox_23")
        self.horizontalLayout_23.addWidget(self.comboBox_23)
        self.gridLayout_14.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_12, 4, 1, 1, 1)
        self.tabWidget.addTab(self.unitConverterTab, "")
        self.mudPumpTab = QtWidgets.QWidget()
        self.mudPumpTab.setObjectName("mudPumpTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mudPumpTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.mudPumpTab)
        self.groupBox.setMaximumSize(QtCore.QSize(400, 650))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem1, 9, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setObjectName("label_40")
        self.gridLayout_15.addWidget(self.label_40, 6, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_15.addWidget(self.lineEdit_21, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.gridLayout_15.addWidget(self.label_26, 13, 0, 1, 1)
        self.comboBox_25 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_25.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_25.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_25.setObjectName("comboBox_25")
        self.gridLayout_15.addWidget(self.comboBox_25, 10, 2, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_7.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_15.addWidget(self.comboBox_7, 2, 2, 1, 1)
        self.comboBox_26 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_26.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_26.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_26.setObjectName("comboBox_26")
        self.gridLayout_15.addWidget(self.comboBox_26, 13, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem2, 1, 0, 1, 1)
        self.linerDiameterCBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.linerDiameterCBox_3.setMinimumSize(QtCore.QSize(70, 0))
        self.linerDiameterCBox_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.linerDiameterCBox_3.setObjectName("linerDiameterCBox_3")
        self.gridLayout_15.addWidget(self.linerDiameterCBox_3, 6, 2, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_15.addWidget(self.lineEdit_32, 6, 1, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_15.addWidget(self.lineEdit_24, 13, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_15.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 10, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem3, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem4, 14, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_15.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_15.addWidget(self.lineEdit_23, 10, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem5, 11, 0, 1, 1)
        self.linerDiameterCBox = QtWidgets.QComboBox(self.groupBox)
        self.linerDiameterCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.linerDiameterCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.linerDiameterCBox.setObjectName("linerDiameterCBox")
        self.gridLayout_15.addWidget(self.linerDiameterCBox, 0, 2, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_27 = QtWidgets.QLabel(self.groupBox_13)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_17.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_13)
        self.label_28.setObjectName("label_28")
        self.gridLayout_17.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_13)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_17.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_13)
        self.label_30.setObjectName("label_30")
        self.gridLayout_17.addWidget(self.label_30, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_13, 21, 0, 1, 3)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.mudPumpTab)
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 650))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_31 = QtWidgets.QLabel(self.groupBox_15)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_18.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_15)
        self.label_32.setObjectName("label_32")
        self.gridLayout_18.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_15)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_18.addWidget(self.label_33, 1, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_15)
        self.label_34.setObjectName("label_34")
        self.gridLayout_18.addWidget(self.label_34, 1, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_15, 19, 0, 1, 3)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_16.addWidget(self.lineEdit_27, 12, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_16.addWidget(self.label_35, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem7, 3, 0, 1, 1)
        self.comboBox_29 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_29.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_29.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_29.setObjectName("comboBox_29")
        self.gridLayout_16.addWidget(self.comboBox_29, 0, 2, 1, 1)
        self.comboBox_30 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_30.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_30.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_30.setObjectName("comboBox_30")
        self.gridLayout_16.addWidget(self.comboBox_30, 14, 2, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_16.addWidget(self.lineEdit_28, 14, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem8, 17, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_16.addWidget(self.lineEdit_30, 0, 1, 1, 1)
        self.comboBox_27 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_27.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_27.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_27.setObjectName("comboBox_27")
        self.gridLayout_16.addWidget(self.comboBox_27, 12, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_16.addWidget(self.label_36, 14, 0, 1, 1)
        self.linerDiameterCBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.linerDiameterCBox_2.setMinimumSize(QtCore.QSize(70, 0))
        self.linerDiameterCBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.linerDiameterCBox_2.setObjectName("linerDiameterCBox_2")
        self.gridLayout_16.addWidget(self.linerDiameterCBox_2, 2, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_16.addWidget(self.label_38, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem9, 13, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_16.addWidget(self.label_39, 12, 0, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_16.addWidget(self.lineEdit_29, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.mudPumpTab, "")
        self.HDOptimizationTab = QtWidgets.QWidget()
        self.HDOptimizationTab.setObjectName("HDOptimizationTab")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.HDOptimizationTab)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_16 = QtWidgets.QGroupBox(self.HDOptimizationTab)
        self.groupBox_16.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_19.setMaximumSize(QtCore.QSize(540, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_49 = QtWidgets.QLabel(self.groupBox_19)
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_3.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.groupBox_19)
        self.label_50.setMinimumSize(QtCore.QSize(50, 0))
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_3.addWidget(self.label_50)
        self.gridLayout_22.addWidget(self.groupBox_19, 0, 4, 4, 1)
        spacerItem10 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem10, 0, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_16)
        self.label_47.setMinimumSize(QtCore.QSize(80, 0))
        self.label_47.setObjectName("label_47")
        self.gridLayout_22.addWidget(self.label_47, 1, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_16)
        self.label_52.setMinimumSize(QtCore.QSize(80, 0))
        self.label_52.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_52.setObjectName("label_52")
        self.gridLayout_22.addWidget(self.label_52, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_16)
        self.label_48.setMinimumSize(QtCore.QSize(0, 0))
        self.label_48.setObjectName("label_48")
        self.gridLayout_22.addWidget(self.label_48, 2, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_22.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_22.addWidget(self.lineEdit_22, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem11, 0, 5, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_38.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_22.addWidget(self.lineEdit_38, 1, 2, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_39.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_22.addWidget(self.lineEdit_39, 2, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_22.addWidget(self.pushButton_3, 1, 3, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_16, 3, 0, 1, 2)
        self.groupBox_14 = QtWidgets.QGroupBox(self.HDOptimizationTab)
        self.groupBox_14.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.tableView = QtWidgets.QTableView(self.groupBox_14)
        self.tableView.setObjectName("tableView")
        self.gridLayout_21.addWidget(self.tableView, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_21.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_21.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_14, 1, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.HDOptimizationTab)
        self.groupBox_17.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_20.addWidget(self.lineEdit_40, 2, 1, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_20.addWidget(self.lineEdit_43, 8, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_17)
        self.label_41.setObjectName("label_41")
        self.gridLayout_20.addWidget(self.label_41, 10, 0, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_20.addWidget(self.lineEdit_41, 4, 1, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_20.addWidget(self.lineEdit_44, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_17)
        self.label_8.setObjectName("label_8")
        self.gridLayout_20.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_20.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_17)
        self.label_42.setObjectName("label_42")
        self.gridLayout_20.addWidget(self.label_42, 6, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_17)
        self.label_37.setObjectName("label_37")
        self.gridLayout_20.addWidget(self.label_37, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_17)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout_20.addWidget(self.label_4, 0, 0, 1, 1)
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_64 = QtWidgets.QLabel(self.groupBox_23)
        self.label_64.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_27.addWidget(self.label_64, 0, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.groupBox_23)
        self.label_65.setObjectName("label_65")
        self.gridLayout_27.addWidget(self.label_65, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_23)
        self.label_43.setObjectName("label_43")
        self.gridLayout_27.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_23)
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.gridLayout_27.addWidget(self.label_44, 1, 1, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_23, 12, 0, 1, 2)
        self.label_62 = QtWidgets.QLabel(self.groupBox_17)
        self.label_62.setObjectName("label_62")
        self.gridLayout_20.addWidget(self.label_62, 8, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem12, 9, 0, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem13, 5, 0, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem14, 7, 0, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem15, 1, 0, 1, 2)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_20.addWidget(self.lineEdit_42, 6, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem16, 3, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_20.addWidget(self.pushButton_4, 11, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_17, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_19.addItem(spacerItem17, 0, 0, 1, 2)
        spacerItem18 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_19.addItem(spacerItem18, 4, 0, 1, 2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_19.addItem(spacerItem19, 2, 0, 1, 2)
        self.tabWidget.addTab(self.HDOptimizationTab, "")
        self.DCAnalysisTab = QtWidgets.QWidget()
        self.DCAnalysisTab.setObjectName("DCAnalysisTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.DCAnalysisTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_18 = QtWidgets.QGroupBox(self.DCAnalysisTab)
        self.groupBox_18.setMaximumSize(QtCore.QSize(600, 600))
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_60 = QtWidgets.QLabel(self.groupBox_18)
        self.label_60.setObjectName("label_60")
        self.gridLayout_23.addWidget(self.label_60, 11, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_18)
        self.label_54.setObjectName("label_54")
        self.gridLayout_23.addWidget(self.label_54, 1, 1, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_23.addWidget(self.lineEdit_35, 7, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox_18)
        self.label_56.setObjectName("label_56")
        self.gridLayout_23.addWidget(self.label_56, 9, 1, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_23.addWidget(self.lineEdit_37, 11, 2, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_55 = QtWidgets.QLabel(self.groupBox_20)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_24.addWidget(self.label_55, 0, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.groupBox_20)
        self.label_61.setObjectName("label_61")
        self.gridLayout_24.addWidget(self.label_61, 0, 1, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_20, 13, 1, 1, 2)
        self.label_53 = QtWidgets.QLabel(self.groupBox_18)
        self.label_53.setObjectName("label_53")
        self.gridLayout_23.addWidget(self.label_53, 5, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.groupBox_18)
        self.label_57.setObjectName("label_57")
        self.gridLayout_23.addWidget(self.label_57, 3, 1, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_23.addWidget(self.lineEdit_33, 3, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem20, 1, 0, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_31.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_23.addWidget(self.lineEdit_31, 1, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.groupBox_18)
        self.label_59.setObjectName("label_59")
        self.gridLayout_23.addWidget(self.label_59, 7, 1, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem21, 1, 3, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_23.addWidget(self.lineEdit_36, 9, 2, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_23.addWidget(self.lineEdit_34, 5, 2, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem22, 14, 1, 1, 2)
        spacerItem23 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem23, 0, 1, 1, 2)
        spacerItem24 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem24, 12, 1, 1, 2)
        spacerItem25 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem25, 10, 1, 1, 2)
        spacerItem26 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem26, 8, 1, 1, 2)
        spacerItem27 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem27, 6, 1, 1, 2)
        spacerItem28 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem28, 4, 1, 1, 2)
        spacerItem29 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem29, 2, 1, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_18, 0, 0, 1, 1)
        self.tabWidget.addTab(self.DCAnalysisTab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_3, self.linerDiameterCBox)
        MainWindow.setTabOrder(self.linerDiameterCBox, self.lineEdit_21)
        MainWindow.setTabOrder(self.lineEdit_21, self.comboBox_7)
        MainWindow.setTabOrder(self.comboBox_7, self.lineEdit_32)
        MainWindow.setTabOrder(self.lineEdit_32, self.linerDiameterCBox_3)
        MainWindow.setTabOrder(self.linerDiameterCBox_3, self.lineEdit_23)
        MainWindow.setTabOrder(self.lineEdit_23, self.comboBox_25)
        MainWindow.setTabOrder(self.comboBox_25, self.lineEdit_24)
        MainWindow.setTabOrder(self.lineEdit_24, self.comboBox_26)
        MainWindow.setTabOrder(self.comboBox_26, self.lineEdit_30)
        MainWindow.setTabOrder(self.lineEdit_30, self.comboBox_29)
        MainWindow.setTabOrder(self.comboBox_29, self.lineEdit_29)
        MainWindow.setTabOrder(self.lineEdit_29, self.linerDiameterCBox_2)
        MainWindow.setTabOrder(self.linerDiameterCBox_2, self.lineEdit_27)
        MainWindow.setTabOrder(self.lineEdit_27, self.comboBox_27)
        MainWindow.setTabOrder(self.comboBox_27, self.lineEdit_28)
        MainWindow.setTabOrder(self.lineEdit_28, self.comboBox_30)
        MainWindow.setTabOrder(self.comboBox_30, self.comboBox_10)
        MainWindow.setTabOrder(self.comboBox_10, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.comboBox_9)
        MainWindow.setTabOrder(self.comboBox_9, self.lineEdit_18)
        MainWindow.setTabOrder(self.lineEdit_18, self.comboBox_20)
        MainWindow.setTabOrder(self.comboBox_20, self.lineEdit_17)
        MainWindow.setTabOrder(self.lineEdit_17, self.comboBox_19)
        MainWindow.setTabOrder(self.comboBox_19, self.lineEdit_10)
        MainWindow.setTabOrder(self.lineEdit_10, self.comboBox_12)
        MainWindow.setTabOrder(self.comboBox_12, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.comboBox_11)
        MainWindow.setTabOrder(self.comboBox_11, self.lineEdit_20)
        MainWindow.setTabOrder(self.lineEdit_20, self.comboBox_22)
        MainWindow.setTabOrder(self.comboBox_22, self.lineEdit_19)
        MainWindow.setTabOrder(self.lineEdit_19, self.comboBox_21)
        MainWindow.setTabOrder(self.comboBox_21, self.lineEdit_12)
        MainWindow.setTabOrder(self.lineEdit_12, self.comboBox_14)
        MainWindow.setTabOrder(self.comboBox_14, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.comboBox_13)
        MainWindow.setTabOrder(self.comboBox_13, self.lineEdit_26)
        MainWindow.setTabOrder(self.lineEdit_26, self.comboBox_24)
        MainWindow.setTabOrder(self.comboBox_24, self.lineEdit_25)
        MainWindow.setTabOrder(self.lineEdit_25, self.comboBox_23)
        MainWindow.setTabOrder(self.comboBox_23, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.comboBox_16)
        MainWindow.setTabOrder(self.comboBox_16, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_13)
        MainWindow.setTabOrder(self.lineEdit_13, self.comboBox_15)
        MainWindow.setTabOrder(self.comboBox_15, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.comboBox_18)
        MainWindow.setTabOrder(self.comboBox_18, self.comboBox_17)
        MainWindow.setTabOrder(self.comboBox_17, self.lineEdit_16)
        MainWindow.setTabOrder(self.lineEdit_16, self.lineEdit_15)
        MainWindow.setTabOrder(self.lineEdit_15, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.comboBox_6)
        MainWindow.setTabOrder(self.comboBox_6, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_14)
        MainWindow.setTabOrder(self.lineEdit_14, self.comboBox_2)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "OPTIDRILL", None, -1))
        self.label_58.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Length", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Temperature", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "Area", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Density", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "Volume", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("MainWindow", "Velocity", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("MainWindow", "Weight", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("MainWindow", "Flowrate", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("MainWindow", "Pressure", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_12.setTitle(QtWidgets.QApplication.translate("MainWindow", "Power", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.unitConverterTab), QtWidgets.QApplication.translate("MainWindow", "Unit Converter", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Duplex Pump", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "Stroke Length ", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Pump Rate", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Liner Diameter", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Volume Efficiency", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Rod Diameter", None, -1))
        self.groupBox_13.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Pump Output:", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Flowrate:", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Triplex Pump", None, -1))
        self.groupBox_15.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Pump Output:", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Flowrate:", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Stroke Length ", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Pump Rate", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "Liner Diameter", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "Volume Efficiency", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mudPumpTab), QtWidgets.QApplication.translate("MainWindow", "Mud Pump", None, -1))
        self.groupBox_16.setTitle(QtWidgets.QApplication.translate("MainWindow", "Optimization", None, -1))
        self.groupBox_19.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.label_49.setText(QtWidgets.QApplication.translate("MainWindow", "Rate Of Penetration-ROP (ft/hr):", None, -1))
        self.label_50.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_47.setText(QtWidgets.QApplication.translate("MainWindow", "WOB (lbm)", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("MainWindow", "RPM (rpm)", None, -1))
        self.label_48.setText(QtWidgets.QApplication.translate("MainWindow", "Impact Force (lbf)", None, -1))
        self.lineEdit_22.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.lineEdit_38.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.lineEdit_39.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "Optimize", None, -1))
        self.groupBox_14.setTitle(QtWidgets.QApplication.translate("MainWindow", "Data", None, -1))
        self.pushButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Import csv or excel data", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Import Data", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Fit", None, -1))
        self.groupBox_17.setTitle(QtWidgets.QApplication.translate("MainWindow", "Hole Cleaning Calculation", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "Flowrate (gpm) ", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Pipe OD (in)", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("MainWindow", "Plastic Viscosity (cP)", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "Mud Weight (ppg)", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Hole ID (in)", None, -1))
        self.label_64.setText(QtWidgets.QApplication.translate("MainWindow", "Carrying Capacity Index - CCI:", None, -1))
        self.label_65.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "Hole Cleaning", None, -1))
        self.label_62.setText(QtWidgets.QApplication.translate("MainWindow", "Yield Point (lb/100ft2) ", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HDOptimizationTab), QtWidgets.QApplication.translate("MainWindow", "Horizontal Drilling Optimization ", None, -1))
        self.label_60.setText(QtWidgets.QApplication.translate("MainWindow", "Footage Drilled", None, -1))
        self.label_54.setText(QtWidgets.QApplication.translate("MainWindow", "Bit Cost ($)", None, -1))
        self.label_56.setText(QtWidgets.QApplication.translate("MainWindow", "Rig Cost per hour ($/hr)", None, -1))
        self.groupBox_20.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.label_55.setText(QtWidgets.QApplication.translate("MainWindow", "Drilled Cost per foot ($/ft)", None, -1))
        self.label_61.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_53.setText(QtWidgets.QApplication.translate("MainWindow", "Footage drilled (ft)", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("MainWindow", "ROP (ft/hr)", None, -1))
        self.label_59.setText(QtWidgets.QApplication.translate("MainWindow", "Round trip (hr)", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DCAnalysisTab), QtWidgets.QApplication.translate("MainWindow", "Drilling Cost Analysis", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

