# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Thu Nov  7 10:59:40 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.homeTab)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.groupBox_21 = QtWidgets.QGroupBox(self.homeTab)
        self.groupBox_21.setMaximumSize(QtCore.QSize(800, 16777215))
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.logoLabel = QtWidgets.QLabel(self.groupBox_21)
        self.logoLabel.setText("")
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout_26.addWidget(self.logoLabel, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_21, 0, 0, 1, 1)
        self.groupBox_22 = QtWidgets.QGroupBox(self.homeTab)
        self.groupBox_22.setMaximumSize(QtCore.QSize(800, 16777215))
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.versionLabel = QtWidgets.QLabel(self.groupBox_22)
        self.versionLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.versionLabel.setText("")
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout_28.addWidget(self.versionLabel, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_22, 1, 0, 1, 1)
        self.tabWidget.addTab(self.homeTab, "")
        self.unitConverterTab = QtWidgets.QWidget()
        self.unitConverterTab.setObjectName("unitConverterTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.unitConverterTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_9.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_9.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.weightFromComboBox = QtWidgets.QComboBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.weightFromComboBox.setFont(font)
        self.weightFromComboBox.setObjectName("weightFromComboBox")
        self.horizontalLayout_12.addWidget(self.weightFromComboBox)
        self.weightFromLineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.weightFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.weightFromLineEdit.setFont(font)
        self.weightFromLineEdit.setObjectName("weightFromLineEdit")
        self.horizontalLayout_12.addWidget(self.weightFromLineEdit)
        self.gridLayout_9.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_9)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.weightToComboBox = QtWidgets.QComboBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.weightToComboBox.setFont(font)
        self.weightToComboBox.setObjectName("weightToComboBox")
        self.horizontalLayout_11.addWidget(self.weightToComboBox)
        self.weightToLineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.weightToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.weightToLineEdit.setFont(font)
        self.weightToLineEdit.setObjectName("weightToLineEdit")
        self.horizontalLayout_11.addWidget(self.weightToLineEdit)
        self.gridLayout_9.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_9, 3, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_10.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_10.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(self.groupBox_10)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        self.flowrateFromComboBox = QtWidgets.QComboBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.flowrateFromComboBox.setFont(font)
        self.flowrateFromComboBox.setObjectName("flowrateFromComboBox")
        self.horizontalLayout_22.addWidget(self.flowrateFromComboBox)
        self.flowrateFromLineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        self.flowrateFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.flowrateFromLineEdit.setFont(font)
        self.flowrateFromLineEdit.setObjectName("flowrateFromLineEdit")
        self.horizontalLayout_22.addWidget(self.flowrateFromLineEdit)
        self.gridLayout_13.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.flowrateToComboBox = QtWidgets.QComboBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.flowrateToComboBox.setFont(font)
        self.flowrateToComboBox.setObjectName("flowrateToComboBox")
        self.horizontalLayout_21.addWidget(self.flowrateToComboBox)
        self.flowrateToLineEdit = QtWidgets.QLineEdit(self.groupBox_10)
        self.flowrateToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.flowrateToLineEdit.setFont(font)
        self.flowrateToLineEdit.setObjectName("flowrateToLineEdit")
        self.horizontalLayout_21.addWidget(self.flowrateToLineEdit)
        self.gridLayout_13.addLayout(self.horizontalLayout_21, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_10, 3, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_7.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_7.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.volumeFromComboBox = QtWidgets.QComboBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.volumeFromComboBox.setFont(font)
        self.volumeFromComboBox.setObjectName("volumeFromComboBox")
        self.horizontalLayout_10.addWidget(self.volumeFromComboBox)
        self.volumeFromLineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.volumeFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.volumeFromLineEdit.setFont(font)
        self.volumeFromLineEdit.setObjectName("volumeFromLineEdit")
        self.horizontalLayout_10.addWidget(self.volumeFromLineEdit)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.volumeToComboBox = QtWidgets.QComboBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.volumeToComboBox.setFont(font)
        self.volumeToComboBox.setObjectName("volumeToComboBox")
        self.horizontalLayout_9.addWidget(self.volumeToComboBox)
        self.volumeToLineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.volumeToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.volumeToLineEdit.setFont(font)
        self.volumeToLineEdit.setObjectName("volumeToLineEdit")
        self.horizontalLayout_9.addWidget(self.volumeToLineEdit)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_7, 2, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_8.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_8.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.velocityFromComboBox = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.velocityFromComboBox.setFont(font)
        self.velocityFromComboBox.setObjectName("velocityFromComboBox")
        self.horizontalLayout_20.addWidget(self.velocityFromComboBox)
        self.velocityFromLineEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.velocityFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.velocityFromLineEdit.setFont(font)
        self.velocityFromLineEdit.setObjectName("velocityFromLineEdit")
        self.horizontalLayout_20.addWidget(self.velocityFromLineEdit)
        self.gridLayout_12.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.velocityToComboBox = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.velocityToComboBox.setFont(font)
        self.velocityToComboBox.setObjectName("velocityToComboBox")
        self.horizontalLayout_19.addWidget(self.velocityToComboBox)
        self.velocityToLineEdit = QtWidgets.QLineEdit(self.groupBox_8)
        self.velocityToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.velocityToLineEdit.setFont(font)
        self.velocityToLineEdit.setObjectName("velocityToLineEdit")
        self.horizontalLayout_19.addWidget(self.velocityToLineEdit)
        self.gridLayout_12.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 2, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_6.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_6.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.densityFromComboBox = QtWidgets.QComboBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.densityFromComboBox.setFont(font)
        self.densityFromComboBox.setObjectName("densityFromComboBox")
        self.horizontalLayout_18.addWidget(self.densityFromComboBox)
        self.densityFromLineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.densityFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.densityFromLineEdit.setFont(font)
        self.densityFromLineEdit.setObjectName("densityFromLineEdit")
        self.horizontalLayout_18.addWidget(self.densityFromLineEdit)
        self.gridLayout_11.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.densityToComboBox = QtWidgets.QComboBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.densityToComboBox.setFont(font)
        self.densityToComboBox.setObjectName("densityToComboBox")
        self.horizontalLayout_17.addWidget(self.densityToComboBox)
        self.densityToLineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.densityToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.densityToLineEdit.setFont(font)
        self.densityToLineEdit.setObjectName("densityToLineEdit")
        self.horizontalLayout_17.addWidget(self.densityToLineEdit)
        self.gridLayout_11.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_3.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lengthFromComboBox = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lengthFromComboBox.setFont(font)
        self.lengthFromComboBox.setObjectName("lengthFromComboBox")
        self.horizontalLayout.addWidget(self.lengthFromComboBox)
        self.lengthFromLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lengthFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lengthFromLineEdit.setFont(font)
        self.lengthFromLineEdit.setObjectName("lengthFromLineEdit")
        self.horizontalLayout.addWidget(self.lengthFromLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lengthToComboBox = QtWidgets.QComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lengthToComboBox.setFont(font)
        self.lengthToComboBox.setObjectName("lengthToComboBox")
        self.horizontalLayout_2.addWidget(self.lengthToComboBox)
        self.lengthToLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lengthToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lengthToLineEdit.setFont(font)
        self.lengthToLineEdit.setObjectName("lengthToLineEdit")
        self.horizontalLayout_2.addWidget(self.lengthToLineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_4.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.tempFromComboBox = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tempFromComboBox.setFont(font)
        self.tempFromComboBox.setObjectName("tempFromComboBox")
        self.horizontalLayout_16.addWidget(self.tempFromComboBox)
        self.tempFromLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.tempFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tempFromLineEdit.setFont(font)
        self.tempFromLineEdit.setObjectName("tempFromLineEdit")
        self.horizontalLayout_16.addWidget(self.tempFromLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.tempToComboBox = QtWidgets.QComboBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tempToComboBox.setFont(font)
        self.tempToComboBox.setObjectName("tempToComboBox")
        self.horizontalLayout_15.addWidget(self.tempToComboBox)
        self.tempToLineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.tempToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.tempToLineEdit.setFont(font)
        self.tempToLineEdit.setObjectName("tempToLineEdit")
        self.horizontalLayout_15.addWidget(self.tempToLineEdit)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_11.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_11.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.pressureFromComboBox = QtWidgets.QComboBox(self.groupBox_11)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pressureFromComboBox.setFont(font)
        self.pressureFromComboBox.setObjectName("pressureFromComboBox")
        self.horizontalLayout_14.addWidget(self.pressureFromComboBox)
        self.pressureFromLineEdit = QtWidgets.QLineEdit(self.groupBox_11)
        self.pressureFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pressureFromLineEdit.setFont(font)
        self.pressureFromLineEdit.setObjectName("pressureFromLineEdit")
        self.horizontalLayout_14.addWidget(self.pressureFromLineEdit)
        self.gridLayout_10.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.pressureToComboBox = QtWidgets.QComboBox(self.groupBox_11)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pressureToComboBox.setFont(font)
        self.pressureToComboBox.setObjectName("pressureToComboBox")
        self.horizontalLayout_13.addWidget(self.pressureToComboBox)
        self.pressureToLineEdit = QtWidgets.QLineEdit(self.groupBox_11)
        self.pressureToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pressureToLineEdit.setFont(font)
        self.pressureToLineEdit.setObjectName("pressureToLineEdit")
        self.horizontalLayout_13.addWidget(self.pressureToLineEdit)
        self.gridLayout_10.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_11, 4, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_12.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_12.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtWidgets.QLabel(self.groupBox_12)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        self.powerFromComboBox = QtWidgets.QComboBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.powerFromComboBox.setFont(font)
        self.powerFromComboBox.setObjectName("powerFromComboBox")
        self.horizontalLayout_24.addWidget(self.powerFromComboBox)
        self.powerFromLineEdit = QtWidgets.QLineEdit(self.groupBox_12)
        self.powerFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.powerFromLineEdit.setFont(font)
        self.powerFromLineEdit.setObjectName("powerFromLineEdit")
        self.horizontalLayout_24.addWidget(self.powerFromLineEdit)
        self.gridLayout_14.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtWidgets.QLabel(self.groupBox_12)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        self.powerToComboBox = QtWidgets.QComboBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.powerToComboBox.setFont(font)
        self.powerToComboBox.setObjectName("powerToComboBox")
        self.horizontalLayout_23.addWidget(self.powerToComboBox)
        self.powerToLineEdit = QtWidgets.QLineEdit(self.groupBox_12)
        self.powerToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.powerToLineEdit.setFont(font)
        self.powerToLineEdit.setObjectName("powerToLineEdit")
        self.horizontalLayout_23.addWidget(self.powerToLineEdit)
        self.gridLayout_14.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_12, 4, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.unitConverterTab)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 100))
        self.groupBox_5.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.areaFromComboBox = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.areaFromComboBox.setFont(font)
        self.areaFromComboBox.setObjectName("areaFromComboBox")
        self.horizontalLayout_6.addWidget(self.areaFromComboBox)
        self.areaFromLineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.areaFromLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.areaFromLineEdit.setFont(font)
        self.areaFromLineEdit.setObjectName("areaFromLineEdit")
        self.horizontalLayout_6.addWidget(self.areaFromLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.areaToComboBox = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.areaToComboBox.setFont(font)
        self.areaToComboBox.setObjectName("areaToComboBox")
        self.horizontalLayout_5.addWidget(self.areaToComboBox)
        self.areaToLineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.areaToLineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.areaToLineEdit.setFont(font)
        self.areaToLineEdit.setObjectName("areaToLineEdit")
        self.horizontalLayout_5.addWidget(self.areaToLineEdit)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.unitConverterTab, "")
        self.mudPumpTab = QtWidgets.QWidget()
        self.mudPumpTab.setObjectName("mudPumpTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mudPumpTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.mudPumpTab)
        self.groupBox.setMaximumSize(QtCore.QSize(400, 650))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setObjectName("label_40")
        self.gridLayout_15.addWidget(self.label_40, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem1, 9, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_15.addWidget(self.label_7, 2, 0, 1, 1)
        self.dLinerDiameterCBox = QtWidgets.QComboBox(self.groupBox)
        self.dLinerDiameterCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.dLinerDiameterCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dLinerDiameterCBox.setObjectName("dLinerDiameterCBox")
        self.gridLayout_15.addWidget(self.dLinerDiameterCBox, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 1)
        self.dRodDiameterLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dRodDiameterLineEdit.setObjectName("dRodDiameterLineEdit")
        self.gridLayout_15.addWidget(self.dRodDiameterLineEdit, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.gridLayout_15.addWidget(self.label_26, 13, 0, 1, 1)
        self.dEfficiencyCBox = QtWidgets.QComboBox(self.groupBox)
        self.dEfficiencyCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.dEfficiencyCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dEfficiencyCBox.setObjectName("dEfficiencyCBox")
        self.gridLayout_15.addWidget(self.dEfficiencyCBox, 10, 2, 1, 1)
        self.dEfficiencyLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dEfficiencyLineEdit.setObjectName("dEfficiencyLineEdit")
        self.gridLayout_15.addWidget(self.dEfficiencyLineEdit, 10, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem2, 5, 0, 1, 1)
        self.dRodDiameterCBox = QtWidgets.QComboBox(self.groupBox)
        self.dRodDiameterCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.dRodDiameterCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dRodDiameterCBox.setObjectName("dRodDiameterCBox")
        self.gridLayout_15.addWidget(self.dRodDiameterCBox, 2, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 10, 0, 1, 1)
        self.dStrokeLengthCBox = QtWidgets.QComboBox(self.groupBox)
        self.dStrokeLengthCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.dStrokeLengthCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dStrokeLengthCBox.setObjectName("dStrokeLengthCBox")
        self.gridLayout_15.addWidget(self.dStrokeLengthCBox, 6, 2, 1, 1)
        self.dPumpRateCBox = QtWidgets.QComboBox(self.groupBox)
        self.dPumpRateCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.dPumpRateCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.dPumpRateCBox.setObjectName("dPumpRateCBox")
        self.gridLayout_15.addWidget(self.dPumpRateCBox, 13, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem4, 11, 0, 1, 1)
        self.dPumpRateLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dPumpRateLineEdit.setObjectName("dPumpRateLineEdit")
        self.gridLayout_15.addWidget(self.dPumpRateLineEdit, 13, 1, 1, 1)
        self.dStrokeLengthLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dStrokeLengthLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dStrokeLengthLineEdit.setObjectName("dStrokeLengthLineEdit")
        self.gridLayout_15.addWidget(self.dStrokeLengthLineEdit, 6, 1, 1, 1)
        self.dLinerDiameterLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.dLinerDiameterLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dLinerDiameterLineEdit.setObjectName("dLinerDiameterLineEdit")
        self.gridLayout_15.addWidget(self.dLinerDiameterLineEdit, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_15.addItem(spacerItem5, 14, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_27 = QtWidgets.QLabel(self.groupBox_13)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_17.addWidget(self.label_27, 1, 0, 1, 1)
        self.duplexFlowrateOutputLabel = QtWidgets.QLabel(self.groupBox_13)
        self.duplexFlowrateOutputLabel.setObjectName("duplexFlowrateOutputLabel")
        self.gridLayout_17.addWidget(self.duplexFlowrateOutputLabel, 2, 1, 1, 1)
        self.duplexPumpOutputLabel = QtWidgets.QLabel(self.groupBox_13)
        self.duplexPumpOutputLabel.setObjectName("duplexPumpOutputLabel")
        self.gridLayout_17.addWidget(self.duplexPumpOutputLabel, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_13)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_17.addWidget(self.label_29, 2, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_13, 21, 0, 1, 3)
        self.dCalculateButton = QtWidgets.QPushButton(self.groupBox)
        self.dCalculateButton.setObjectName("dCalculateButton")
        self.gridLayout_15.addWidget(self.dCalculateButton, 14, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.mudPumpTab)
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 650))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_31 = QtWidgets.QLabel(self.groupBox_15)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_18.addWidget(self.label_31, 0, 0, 1, 1)
        self.triplexPumpOutputLabel = QtWidgets.QLabel(self.groupBox_15)
        self.triplexPumpOutputLabel.setObjectName("triplexPumpOutputLabel")
        self.gridLayout_18.addWidget(self.triplexPumpOutputLabel, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_15)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_18.addWidget(self.label_33, 1, 0, 1, 1)
        self.triplexFlowrateOutputLabel = QtWidgets.QLabel(self.groupBox_15)
        self.triplexFlowrateOutputLabel.setObjectName("triplexFlowrateOutputLabel")
        self.gridLayout_18.addWidget(self.triplexFlowrateOutputLabel, 1, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_15, 19, 0, 1, 3)
        self.tEfficiencyLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tEfficiencyLineEdit.setObjectName("tEfficiencyLineEdit")
        self.gridLayout_16.addWidget(self.tEfficiencyLineEdit, 12, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_16.addWidget(self.label_35, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem7, 3, 0, 1, 1)
        self.tLinerDiameterCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.tLinerDiameterCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tLinerDiameterCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tLinerDiameterCBox.setObjectName("tLinerDiameterCBox")
        self.gridLayout_16.addWidget(self.tLinerDiameterCBox, 0, 2, 1, 1)
        self.tPumpRateCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.tPumpRateCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tPumpRateCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tPumpRateCBox.setObjectName("tPumpRateCBox")
        self.gridLayout_16.addWidget(self.tPumpRateCBox, 14, 2, 1, 1)
        self.tPumpRateLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tPumpRateLineEdit.setObjectName("tPumpRateLineEdit")
        self.gridLayout_16.addWidget(self.tPumpRateLineEdit, 14, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem8, 17, 0, 1, 1)
        self.tLinerDiameterLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tLinerDiameterLineEdit.setObjectName("tLinerDiameterLineEdit")
        self.gridLayout_16.addWidget(self.tLinerDiameterLineEdit, 0, 1, 1, 1)
        self.tEfficiencyCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.tEfficiencyCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tEfficiencyCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tEfficiencyCBox.setObjectName("tEfficiencyCBox")
        self.gridLayout_16.addWidget(self.tEfficiencyCBox, 12, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_16.addWidget(self.label_36, 14, 0, 1, 1)
        self.tStrokeLengthCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.tStrokeLengthCBox.setMinimumSize(QtCore.QSize(70, 0))
        self.tStrokeLengthCBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.tStrokeLengthCBox.setObjectName("tStrokeLengthCBox")
        self.gridLayout_16.addWidget(self.tStrokeLengthCBox, 2, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_16.addWidget(self.label_38, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_16.addItem(spacerItem9, 13, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_16.addWidget(self.label_39, 12, 0, 1, 1)
        self.tStrokeLengthLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tStrokeLengthLineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tStrokeLengthLineEdit.setObjectName("tStrokeLengthLineEdit")
        self.gridLayout_16.addWidget(self.tStrokeLengthLineEdit, 2, 1, 1, 1)
        self.tCalculateButton = QtWidgets.QPushButton(self.groupBox_2)
        self.tCalculateButton.setObjectName("tCalculateButton")
        self.gridLayout_16.addWidget(self.tCalculateButton, 17, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.mudPumpTab, "")
        self.HDOptimizationTab = QtWidgets.QWidget()
        self.HDOptimizationTab.setObjectName("HDOptimizationTab")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.HDOptimizationTab)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_16 = QtWidgets.QGroupBox(self.HDOptimizationTab)
        self.groupBox_16.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_19.setMaximumSize(QtCore.QSize(540, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ROPLabel = QtWidgets.QLabel(self.groupBox_19)
        self.ROPLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ROPLabel.setObjectName("ROPLabel")
        self.horizontalLayout_3.addWidget(self.ROPLabel)
        self.ROPOutputLabel = QtWidgets.QLabel(self.groupBox_19)
        self.ROPOutputLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.ROPOutputLabel.setObjectName("ROPOutputLabel")
        self.horizontalLayout_3.addWidget(self.ROPOutputLabel)
        self.gridLayout_22.addWidget(self.groupBox_19, 0, 4, 5, 1)
        self.WOBLineEdit = QtWidgets.QLineEdit(self.groupBox_16)
        self.WOBLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.WOBLineEdit.setObjectName("WOBLineEdit")
        self.gridLayout_22.addWidget(self.WOBLineEdit, 0, 2, 1, 1)
        self.mudWeightLineEdit2 = QtWidgets.QLineEdit(self.groupBox_16)
        self.mudWeightLineEdit2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.mudWeightLineEdit2.setObjectName("mudWeightLineEdit2")
        self.gridLayout_22.addWidget(self.mudWeightLineEdit2, 3, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem10, 0, 0, 1, 1)
        self.RPMLineEdit = QtWidgets.QLineEdit(self.groupBox_16)
        self.RPMLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.RPMLineEdit.setObjectName("RPMLineEdit")
        self.gridLayout_22.addWidget(self.RPMLineEdit, 1, 2, 1, 1)
        self.mudWeightLabel_2 = QtWidgets.QLabel(self.groupBox_16)
        self.mudWeightLabel_2.setObjectName("mudWeightLabel_2")
        self.gridLayout_22.addWidget(self.mudWeightLabel_2, 3, 1, 1, 1)
        self.RPMLabel = QtWidgets.QLabel(self.groupBox_16)
        self.RPMLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.RPMLabel.setObjectName("RPMLabel")
        self.gridLayout_22.addWidget(self.RPMLabel, 1, 1, 1, 1)
        self.impactForceLabel = QtWidgets.QLabel(self.groupBox_16)
        self.impactForceLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.impactForceLabel.setObjectName("impactForceLabel")
        self.gridLayout_22.addWidget(self.impactForceLabel, 2, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem11, 0, 5, 1, 1)
        self.optFlowrateLabel = QtWidgets.QLabel(self.groupBox_16)
        self.optFlowrateLabel.setObjectName("optFlowrateLabel")
        self.gridLayout_22.addWidget(self.optFlowrateLabel, 4, 1, 1, 1)
        self.impactForceLineEdit = QtWidgets.QLineEdit(self.groupBox_16)
        self.impactForceLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.impactForceLineEdit.setObjectName("impactForceLineEdit")
        self.gridLayout_22.addWidget(self.impactForceLineEdit, 2, 2, 1, 1)
        self.WOBLabel = QtWidgets.QLabel(self.groupBox_16)
        self.WOBLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.WOBLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.WOBLabel.setObjectName("WOBLabel")
        self.gridLayout_22.addWidget(self.WOBLabel, 0, 1, 1, 1)
        self.flowrateLineEdit2 = QtWidgets.QLineEdit(self.groupBox_16)
        self.flowrateLineEdit2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.flowrateLineEdit2.setObjectName("flowrateLineEdit2")
        self.gridLayout_22.addWidget(self.flowrateLineEdit2, 4, 2, 1, 1)
        self.optimizeButton = QtWidgets.QPushButton(self.groupBox_16)
        self.optimizeButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.optimizeButton.setObjectName("optimizeButton")
        self.gridLayout_22.addWidget(self.optimizeButton, 1, 3, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_16, 3, 0, 1, 2)
        self.groupBox_14 = QtWidgets.QGroupBox(self.HDOptimizationTab)
        self.groupBox_14.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.dataTableView = QtWidgets.QTableView(self.groupBox_14)
        self.dataTableView.setObjectName("dataTableView")
        self.gridLayout_21.addWidget(self.dataTableView, 1, 1, 1, 1)
        self.importDataButton = QtWidgets.QPushButton(self.groupBox_14)
        self.importDataButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.importDataButton.setObjectName("importDataButton")
        self.gridLayout_21.addWidget(self.importDataButton, 0, 0, 1, 1)
        self.fitButton = QtWidgets.QPushButton(self.groupBox_14)
        self.fitButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fitButton.setObjectName("fitButton")
        self.gridLayout_21.addWidget(self.fitButton, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_14, 1, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.HDOptimizationTab)
        self.groupBox_17.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.CCILabel = QtWidgets.QLabel(self.groupBox_23)
        self.CCILabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CCILabel.setObjectName("CCILabel")
        self.gridLayout_27.addWidget(self.CCILabel, 0, 0, 1, 1)
        self.CCIOutputLabel = QtWidgets.QLabel(self.groupBox_23)
        self.CCIOutputLabel.setObjectName("CCIOutputLabel")
        self.gridLayout_27.addWidget(self.CCIOutputLabel, 0, 1, 1, 1)
        self.holeCleaningLabel = QtWidgets.QLabel(self.groupBox_23)
        self.holeCleaningLabel.setObjectName("holeCleaningLabel")
        self.gridLayout_27.addWidget(self.holeCleaningLabel, 1, 0, 1, 1)
        self.holeCleaningOutputLabel = QtWidgets.QLabel(self.groupBox_23)
        self.holeCleaningOutputLabel.setText("")
        self.holeCleaningOutputLabel.setObjectName("holeCleaningOutputLabel")
        self.gridLayout_27.addWidget(self.holeCleaningOutputLabel, 1, 1, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_23, 12, 0, 1, 2)
        self.pipeODLineEdit = QtWidgets.QLineEdit(self.groupBox_17)
        self.pipeODLineEdit.setObjectName("pipeODLineEdit")
        self.gridLayout_20.addWidget(self.pipeODLineEdit, 2, 1, 1, 1)
        self.pipeODLabel = QtWidgets.QLabel(self.groupBox_17)
        self.pipeODLabel.setObjectName("pipeODLabel")
        self.gridLayout_20.addWidget(self.pipeODLabel, 2, 0, 1, 1)
        self.holeIDLineEdit = QtWidgets.QLineEdit(self.groupBox_17)
        self.holeIDLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.holeIDLineEdit.setObjectName("holeIDLineEdit")
        self.gridLayout_20.addWidget(self.holeIDLineEdit, 0, 1, 1, 1)
        self.plasticViscosityLabel = QtWidgets.QLabel(self.groupBox_17)
        self.plasticViscosityLabel.setObjectName("plasticViscosityLabel")
        self.gridLayout_20.addWidget(self.plasticViscosityLabel, 6, 0, 1, 1)
        self.mudWeightLabel = QtWidgets.QLabel(self.groupBox_17)
        self.mudWeightLabel.setObjectName("mudWeightLabel")
        self.gridLayout_20.addWidget(self.mudWeightLabel, 4, 0, 1, 1)
        self.holeIDLabel = QtWidgets.QLabel(self.groupBox_17)
        self.holeIDLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.holeIDLabel.setObjectName("holeIDLabel")
        self.gridLayout_20.addWidget(self.holeIDLabel, 0, 0, 1, 1)
        self.yieldPointLabel = QtWidgets.QLabel(self.groupBox_17)
        self.yieldPointLabel.setObjectName("yieldPointLabel")
        self.gridLayout_20.addWidget(self.yieldPointLabel, 8, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem12, 9, 0, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem13, 5, 0, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem14, 7, 0, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem15, 1, 0, 1, 2)
        self.plasticViscosityLineEdit = QtWidgets.QLineEdit(self.groupBox_17)
        self.plasticViscosityLineEdit.setObjectName("plasticViscosityLineEdit")
        self.gridLayout_20.addWidget(self.plasticViscosityLineEdit, 6, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_20.addItem(spacerItem16, 3, 0, 1, 2)
        self.calculateButton = QtWidgets.QPushButton(self.groupBox_17)
        self.calculateButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.calculateButton.setObjectName("calculateButton")
        self.gridLayout_20.addWidget(self.calculateButton, 11, 0, 1, 1)
        self.mudWeightLineEdit1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.mudWeightLineEdit1.setObjectName("mudWeightLineEdit1")
        self.gridLayout_20.addWidget(self.mudWeightLineEdit1, 4, 1, 1, 1)
        self.yieldPointLineEdit = QtWidgets.QLineEdit(self.groupBox_17)
        self.yieldPointLineEdit.setObjectName("yieldPointLineEdit")
        self.gridLayout_20.addWidget(self.yieldPointLineEdit, 8, 1, 1, 1)
        self.flowrateLineEdit1 = QtWidgets.QLineEdit(self.groupBox_17)
        self.flowrateLineEdit1.setObjectName("flowrateLineEdit1")
        self.gridLayout_20.addWidget(self.flowrateLineEdit1, 10, 1, 1, 1)
        self.flowrateLabel = QtWidgets.QLabel(self.groupBox_17)
        self.flowrateLabel.setObjectName("flowrateLabel")
        self.gridLayout_20.addWidget(self.flowrateLabel, 10, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_17, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_19.addItem(spacerItem17, 0, 0, 1, 2)
        spacerItem18 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_19.addItem(spacerItem18, 4, 0, 1, 2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_19.addItem(spacerItem19, 2, 0, 1, 2)
        self.tabWidget.addTab(self.HDOptimizationTab, "")
        self.DCAnalysisTab = QtWidgets.QWidget()
        self.DCAnalysisTab.setObjectName("DCAnalysisTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.DCAnalysisTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_18 = QtWidgets.QGroupBox(self.DCAnalysisTab)
        self.groupBox_18.setMaximumSize(QtCore.QSize(600, 600))
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_55 = QtWidgets.QLabel(self.groupBox_20)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_24.addWidget(self.label_55, 0, 0, 1, 1)
        self.drilledCostOutputLabel = QtWidgets.QLabel(self.groupBox_20)
        self.drilledCostOutputLabel.setObjectName("drilledCostOutputLabel")
        self.gridLayout_24.addWidget(self.drilledCostOutputLabel, 0, 1, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_20, 13, 1, 1, 2)
        self.calculateCostButton = QtWidgets.QPushButton(self.groupBox_18)
        self.calculateCostButton.setObjectName("calculateCostButton")
        self.gridLayout_23.addWidget(self.calculateCostButton, 11, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem20, 12, 1, 1, 2)
        spacerItem21 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem21, 8, 1, 1, 2)
        spacerItem22 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem22, 4, 1, 1, 2)
        spacerItem23 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem23, 0, 1, 1, 2)
        spacerItem24 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem24, 2, 1, 1, 2)
        spacerItem25 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem25, 14, 1, 1, 2)
        self.rigCostLineEdit = QtWidgets.QLineEdit(self.groupBox_18)
        self.rigCostLineEdit.setObjectName("rigCostLineEdit")
        self.gridLayout_23.addWidget(self.rigCostLineEdit, 9, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox_18)
        self.label_56.setObjectName("label_56")
        self.gridLayout_23.addWidget(self.label_56, 9, 1, 1, 1)
        self.ROPLineEdit = QtWidgets.QLineEdit(self.groupBox_18)
        self.ROPLineEdit.setObjectName("ROPLineEdit")
        self.gridLayout_23.addWidget(self.ROPLineEdit, 3, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBox_18)
        self.label_53.setObjectName("label_53")
        self.gridLayout_23.addWidget(self.label_53, 5, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_18)
        self.label_54.setObjectName("label_54")
        self.gridLayout_23.addWidget(self.label_54, 1, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_23.addItem(spacerItem26, 6, 1, 1, 2)
        self.label_57 = QtWidgets.QLabel(self.groupBox_18)
        self.label_57.setObjectName("label_57")
        self.gridLayout_23.addWidget(self.label_57, 3, 1, 1, 1)
        self.footageDrilledLineEdit = QtWidgets.QLineEdit(self.groupBox_18)
        self.footageDrilledLineEdit.setObjectName("footageDrilledLineEdit")
        self.gridLayout_23.addWidget(self.footageDrilledLineEdit, 5, 2, 1, 1)
        self.roundTripLineEdit = QtWidgets.QLineEdit(self.groupBox_18)
        self.roundTripLineEdit.setObjectName("roundTripLineEdit")
        self.gridLayout_23.addWidget(self.roundTripLineEdit, 7, 2, 1, 1)
        self.bitCostLineEdit = QtWidgets.QLineEdit(self.groupBox_18)
        self.bitCostLineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.bitCostLineEdit.setObjectName("bitCostLineEdit")
        self.gridLayout_23.addWidget(self.bitCostLineEdit, 1, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem27, 1, 0, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem28, 1, 3, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.groupBox_18)
        self.label_59.setObjectName("label_59")
        self.gridLayout_23.addWidget(self.label_59, 7, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_23.addItem(spacerItem29, 10, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_18, 0, 0, 1, 1)
        self.tabWidget.addTab(self.DCAnalysisTab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lengthFromComboBox, self.lengthFromLineEdit)
        MainWindow.setTabOrder(self.lengthFromLineEdit, self.lengthToComboBox)
        MainWindow.setTabOrder(self.lengthToComboBox, self.lengthToLineEdit)
        MainWindow.setTabOrder(self.lengthToLineEdit, self.areaFromComboBox)
        MainWindow.setTabOrder(self.areaFromComboBox, self.areaFromLineEdit)
        MainWindow.setTabOrder(self.areaFromLineEdit, self.areaToComboBox)
        MainWindow.setTabOrder(self.areaToComboBox, self.areaToLineEdit)
        MainWindow.setTabOrder(self.areaToLineEdit, self.volumeFromComboBox)
        MainWindow.setTabOrder(self.volumeFromComboBox, self.volumeFromLineEdit)
        MainWindow.setTabOrder(self.volumeFromLineEdit, self.volumeToComboBox)
        MainWindow.setTabOrder(self.volumeToComboBox, self.volumeToLineEdit)
        MainWindow.setTabOrder(self.volumeToLineEdit, self.weightFromComboBox)
        MainWindow.setTabOrder(self.weightFromComboBox, self.weightFromLineEdit)
        MainWindow.setTabOrder(self.weightFromLineEdit, self.weightToComboBox)
        MainWindow.setTabOrder(self.weightToComboBox, self.weightToLineEdit)
        MainWindow.setTabOrder(self.weightToLineEdit, self.pressureFromComboBox)
        MainWindow.setTabOrder(self.pressureFromComboBox, self.pressureFromLineEdit)
        MainWindow.setTabOrder(self.pressureFromLineEdit, self.pressureToComboBox)
        MainWindow.setTabOrder(self.pressureToComboBox, self.pressureToLineEdit)
        MainWindow.setTabOrder(self.pressureToLineEdit, self.tempFromComboBox)
        MainWindow.setTabOrder(self.tempFromComboBox, self.tempFromLineEdit)
        MainWindow.setTabOrder(self.tempFromLineEdit, self.tempToComboBox)
        MainWindow.setTabOrder(self.tempToComboBox, self.tempToLineEdit)
        MainWindow.setTabOrder(self.tempToLineEdit, self.densityFromComboBox)
        MainWindow.setTabOrder(self.densityFromComboBox, self.densityFromLineEdit)
        MainWindow.setTabOrder(self.densityFromLineEdit, self.densityToComboBox)
        MainWindow.setTabOrder(self.densityToComboBox, self.densityToLineEdit)
        MainWindow.setTabOrder(self.densityToLineEdit, self.velocityFromComboBox)
        MainWindow.setTabOrder(self.velocityFromComboBox, self.velocityFromLineEdit)
        MainWindow.setTabOrder(self.velocityFromLineEdit, self.velocityToComboBox)
        MainWindow.setTabOrder(self.velocityToComboBox, self.velocityToLineEdit)
        MainWindow.setTabOrder(self.velocityToLineEdit, self.flowrateFromComboBox)
        MainWindow.setTabOrder(self.flowrateFromComboBox, self.flowrateFromLineEdit)
        MainWindow.setTabOrder(self.flowrateFromLineEdit, self.flowrateToComboBox)
        MainWindow.setTabOrder(self.flowrateToComboBox, self.flowrateToLineEdit)
        MainWindow.setTabOrder(self.flowrateToLineEdit, self.powerFromComboBox)
        MainWindow.setTabOrder(self.powerFromComboBox, self.powerFromLineEdit)
        MainWindow.setTabOrder(self.powerFromLineEdit, self.powerToComboBox)
        MainWindow.setTabOrder(self.powerToComboBox, self.powerToLineEdit)
        MainWindow.setTabOrder(self.powerToLineEdit, self.dLinerDiameterLineEdit)
        MainWindow.setTabOrder(self.dLinerDiameterLineEdit, self.dLinerDiameterCBox)
        MainWindow.setTabOrder(self.dLinerDiameterCBox, self.dRodDiameterLineEdit)
        MainWindow.setTabOrder(self.dRodDiameterLineEdit, self.dRodDiameterCBox)
        MainWindow.setTabOrder(self.dRodDiameterCBox, self.dStrokeLengthLineEdit)
        MainWindow.setTabOrder(self.dStrokeLengthLineEdit, self.dStrokeLengthCBox)
        MainWindow.setTabOrder(self.dStrokeLengthCBox, self.dEfficiencyLineEdit)
        MainWindow.setTabOrder(self.dEfficiencyLineEdit, self.dEfficiencyCBox)
        MainWindow.setTabOrder(self.dEfficiencyCBox, self.dPumpRateLineEdit)
        MainWindow.setTabOrder(self.dPumpRateLineEdit, self.dPumpRateCBox)
        MainWindow.setTabOrder(self.dPumpRateCBox, self.dCalculateButton)
        MainWindow.setTabOrder(self.dCalculateButton, self.tLinerDiameterLineEdit)
        MainWindow.setTabOrder(self.tLinerDiameterLineEdit, self.tLinerDiameterCBox)
        MainWindow.setTabOrder(self.tLinerDiameterCBox, self.tStrokeLengthLineEdit)
        MainWindow.setTabOrder(self.tStrokeLengthLineEdit, self.tStrokeLengthCBox)
        MainWindow.setTabOrder(self.tStrokeLengthCBox, self.tEfficiencyLineEdit)
        MainWindow.setTabOrder(self.tEfficiencyLineEdit, self.tEfficiencyCBox)
        MainWindow.setTabOrder(self.tEfficiencyCBox, self.tPumpRateLineEdit)
        MainWindow.setTabOrder(self.tPumpRateLineEdit, self.tPumpRateCBox)
        MainWindow.setTabOrder(self.tPumpRateCBox, self.tCalculateButton)
        MainWindow.setTabOrder(self.tCalculateButton, self.importDataButton)
        MainWindow.setTabOrder(self.importDataButton, self.dataTableView)
        MainWindow.setTabOrder(self.dataTableView, self.fitButton)
        MainWindow.setTabOrder(self.fitButton, self.holeIDLineEdit)
        MainWindow.setTabOrder(self.holeIDLineEdit, self.pipeODLineEdit)
        MainWindow.setTabOrder(self.pipeODLineEdit, self.mudWeightLineEdit1)
        MainWindow.setTabOrder(self.mudWeightLineEdit1, self.plasticViscosityLineEdit)
        MainWindow.setTabOrder(self.plasticViscosityLineEdit, self.yieldPointLineEdit)
        MainWindow.setTabOrder(self.yieldPointLineEdit, self.flowrateLineEdit1)
        MainWindow.setTabOrder(self.flowrateLineEdit1, self.calculateButton)
        MainWindow.setTabOrder(self.calculateButton, self.WOBLineEdit)
        MainWindow.setTabOrder(self.WOBLineEdit, self.RPMLineEdit)
        MainWindow.setTabOrder(self.RPMLineEdit, self.impactForceLineEdit)
        MainWindow.setTabOrder(self.impactForceLineEdit, self.mudWeightLineEdit2)
        MainWindow.setTabOrder(self.mudWeightLineEdit2, self.flowrateLineEdit2)
        MainWindow.setTabOrder(self.flowrateLineEdit2, self.optimizeButton)
        MainWindow.setTabOrder(self.optimizeButton, self.bitCostLineEdit)
        MainWindow.setTabOrder(self.bitCostLineEdit, self.ROPLineEdit)
        MainWindow.setTabOrder(self.ROPLineEdit, self.footageDrilledLineEdit)
        MainWindow.setTabOrder(self.footageDrilledLineEdit, self.roundTripLineEdit)
        MainWindow.setTabOrder(self.roundTripLineEdit, self.rigCostLineEdit)
        MainWindow.setTabOrder(self.rigCostLineEdit, self.calculateCostButton)
        MainWindow.setTabOrder(self.calculateCostButton, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "OPTIDRILL", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("MainWindow", "Weight", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("MainWindow", "Flowrate", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "Volume", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("MainWindow", "Velocity", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Density", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Length", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Temperature", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("MainWindow", "Pressure", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_12.setTitle(QtWidgets.QApplication.translate("MainWindow", "Power", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "Area", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.unitConverterTab), QtWidgets.QApplication.translate("MainWindow", "Unit Converter", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Duplex Pump", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "Stroke Length", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Rod Diameter", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Liner Diameter", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Pump Rate", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Efficiency", None, -1))
        self.groupBox_13.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Pump Output:", None, -1))
        self.duplexFlowrateOutputLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.duplexPumpOutputLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Flowrate:", None, -1))
        self.dCalculateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Triplex Pump", None, -1))
        self.groupBox_15.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Pump Output:", None, -1))
        self.triplexPumpOutputLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Flowrate:", None, -1))
        self.triplexFlowrateOutputLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Stroke Length", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Pump Rate", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "Liner Diameter", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "Efficiency", None, -1))
        self.tCalculateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mudPumpTab), QtWidgets.QApplication.translate("MainWindow", "Mud Pump", None, -1))
        self.groupBox_16.setTitle(QtWidgets.QApplication.translate("MainWindow", "Optimization", None, -1))
        self.groupBox_19.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.ROPLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Rate Of Penetration-ROP (ft/hr):", None, -1))
        self.ROPOutputLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.WOBLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.RPMLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.mudWeightLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "Mud Weight-MW (ppg)", None, -1))
        self.RPMLabel.setText(QtWidgets.QApplication.translate("MainWindow", "RPM (rpm)", None, -1))
        self.impactForceLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Impact Force (lbf)", None, -1))
        self.optFlowrateLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Flowrate (gpm)", None, -1))
        self.impactForceLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.WOBLabel.setText(QtWidgets.QApplication.translate("MainWindow", "WOB (lbm)", None, -1))
        self.optimizeButton.setText(QtWidgets.QApplication.translate("MainWindow", "Optimize", None, -1))
        self.groupBox_14.setTitle(QtWidgets.QApplication.translate("MainWindow", "Data", None, -1))
        self.importDataButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Import csv or excel data", None, -1))
        self.importDataButton.setText(QtWidgets.QApplication.translate("MainWindow", "Import Data", None, -1))
        self.fitButton.setText(QtWidgets.QApplication.translate("MainWindow", "Fit", None, -1))
        self.groupBox_17.setTitle(QtWidgets.QApplication.translate("MainWindow", "Hole Cleaning Calculation", None, -1))
        self.CCILabel.setText(QtWidgets.QApplication.translate("MainWindow", "Carrying Capacity Index - CCI:", None, -1))
        self.CCIOutputLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.holeCleaningLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Hole Cleaning", None, -1))
        self.pipeODLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Pipe OD (in)", None, -1))
        self.plasticViscosityLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Plastic Viscosity (cP)", None, -1))
        self.mudWeightLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Mud Weight (ppg)", None, -1))
        self.holeIDLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Hole ID (in)", None, -1))
        self.yieldPointLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Yield Point (lb/100sq.ft) ", None, -1))
        self.calculateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.flowrateLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Flowrate (gpm) ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HDOptimizationTab), QtWidgets.QApplication.translate("MainWindow", "Horizontal Drilling Optimization ", None, -1))
        self.groupBox_20.setTitle(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.label_55.setText(QtWidgets.QApplication.translate("MainWindow", "Drilled Cost per foot", None, -1))
        self.drilledCostOutputLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.calculateCostButton.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.label_56.setText(QtWidgets.QApplication.translate("MainWindow", "Rig Cost per hour ($/hr)", None, -1))
        self.label_53.setText(QtWidgets.QApplication.translate("MainWindow", "Footage Drilled (ft)", None, -1))
        self.label_54.setText(QtWidgets.QApplication.translate("MainWindow", "Bit Cost ($)", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("MainWindow", "ROP (ft/hr)", None, -1))
        self.label_59.setText(QtWidgets.QApplication.translate("MainWindow", "Round trip (hr)", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DCAnalysisTab), QtWidgets.QApplication.translate("MainWindow", "Drilling Cost Analysis", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

